eureka:
  instance:
    hostname: guidance-config-service.herokuapp.com
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://guidance-discovery-service.herokuapp.com/eureka/
spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/skripsirifyal/config-repo
          skip-ssl-validation: true
          clone-on-start: true
          search-paths: 'config-repo, config-repo/{application}'
        bootstrap: true
  security:
    user:
      name: root
      password: 4c4d3mIc5ec12eT

server:
  port: 8888